# Generated by Django 4.2.7 on 2023-11-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, unique=True, verbose_name='User First Name')),
                ('last_name', models.CharField(max_length=60, unique=True, verbose_name='User Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('address', models.CharField(max_length=360, verbose_name='User Address')),
                ('post_code', models.CharField(max_length=20, verbose_name='User Post Code')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=360, verbose_name='Venue Address')),
                ('post_code', models.CharField(max_length=20, verbose_name='Venue Post Code')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Venue Email')),
                ('web_address', models.URLField(verbose_name='Venue Website')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Event Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=120, verbose_name='Event Name')),
                ('description', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='event_attendee', to='events.user')),
                ('venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.venue')),
            ],
        ),
    ]
