# Generated by Django 4.2.7 on 2023-11-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(max_length=120, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_location', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=360, verbose_name='User Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='User Post Code'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Venue Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web_address',
            field=models.URLField(blank=True, verbose_name='Venue Website'),
        ),
    ]
